name: Client CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "client/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Build the project
        working-directory: ./client
        run: npm run build
        env:
          VITE_SQUARE_API_BASE_URL_PRODUCTION: ${{ secrets.VITE_SQUARE_API_BASE_URL_PRODUCTION }}
          VITE_ENVIRONMENT: ${{ secrets.VITE_ENVIRONMENT }}

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'upload'
          app_location: 'client'
          output_location: 'dist'
